### ISSUE TITLE
Publishing the package to PyPI

### ISSUE THREAD

**Issue by amotl** [metwork-framework/cronwrapper#16]
Hi @thefab, @Hawker65 and @thebaptiste,

thanks for conceiving this excellent program. I just found it indirectly through [1].

Extending my research, there is also
- [`cronwrap`](https://github.com/Doist/cronwrap) by @lowks, @imankulov and @desktable on behalf of @Doist
- [`croncoat`](https://github.com/MatthiasKauer/croncoat) by @MatthiasKauer with contributions from @lowks, @KeyMasterOfGozer and @imankulov
- Another [`cronwrap`](https://github.com/jonyesno/cronwrap) by @jonyesno written in Ruby
- [`lockrun`](http://unixwiz.net/tools/lockrun.html) by @SJFriedl written in Bash
- ... and probably more.

`cronwrap` and `croncoat` are already available on PyPI [2,3] and there is also another tool called `cronwrapper` [4]. However, the release package of `cronwrapper` available on PyPI apparently does not even include any code. After looking inside, I found it might have been conceived by Banio Carpenter (@baniobloom) and is currently maintained by @ranamalo, who also hosts its source code at [5].

However, all the Python implementations apparently didn't receive any commits within the last two years. I didn't investigate thoroughly if some features might be missing compared to the other tools, but I believe your variant to be pretty complete and advanced from my perspective.

So, it would be really nice to see your variant of `cronwrapper` to be published to PyPI in any way. However, as the name is already taken on PyPI, we might either ask @baniobloom or @ranamalo whether they want to carry on with their variant of `cronwrapper` or you might think about giving your variant a different name.

With kind regards,
Andreas.

[1] https://askubuntu.com/questions/179943/getting-notified-of-failed-cron-jobs
[2] https://pypi.org/project/cronwrap/
[3] https://pypi.org/project/croncoat/
[4] https://pypi.org/project/cronwrapper/
[5] https://github.com/ranamalo/cronwrapper

**Comment by thefab** [comment]
cron-wrapper? (with a `-`)

**Comment by thefab** [comment]
https://pypi.org/project/cron-wrapper/
=> available 
(but not uploaded ! ;-))

**Comment by thefab** [comment]
- [x] choose name: `cron-wrapper`
- [x] rename repo
- [x] merge #18 
- [x] add github action to build/test/publish to pypi

**Comment by thefab** [comment]
published! @amotl: can you check it's ok for you?

**Comment by amotl** [comment]
Hi Fabien,

thanks a stack. Installing the package from PyPI works like a charm. I appreciate your responsiveness on this excellent ride.

Have a good weekend and with kind regards,
Andreas.

**Comment by ranamalo** [comment]
I'm a little late to the party but one of the reasons I created cronwrapper originally was to be notified on failed cron jobs on boxes that did not have mail configured by sending those errors from a uniform error email account.  Those errors were sometimes non-zero exit statuses and sometimes scripts that exited with status 0 but had output to stderr.
